## 1. 파이썬 파일 처리

In [108]:
sample_file = '../data/sample_data.txt'

In [127]:
# 파일을 open하여 전체 내용을 읽어서 출력
with open(sample_file, mode='rt', encoding='utf-8') as f:
    content = f.read()
    print(content)

print("----- 끝 -----")

Name,Age,Gender,City
Alice,24.0,F,New York
Bob,,M,Los Angeles
Charlie,22.0,M,
David,29.0,M,Chicago
Edward,,M,Houston
Alice,24.0,F,New York
Susan,32.0,F,Houston

----- 끝 -----

In [128]:
# 파일을 open하고 한 줄씩 읽어서 출력하기
with open(sample_file, 'r') as f:
    lines = f.readlines()

print("----- 끝 -----")

----- 끝 -----

In [129]:
# 파일객체에서 한 줄씩 읽어 오기
# 파일 객체 f를 반복문에서 사용하면 파일을 한 줄씩 읽으며,
# 각 줄 끝의 \n도 포함해서 가져옵
with open(sample_file, 'r') as f:
    line = f.readline()
    

print("----- 끝 -----")

----- 끝 -----

In [130]:
# 여러 개의 파일 읽기 (모든 txt 파일을 읽어서 출력하기)
import glob
txt_file_pattern = "data/*.csv"
files = glob.glob(txt_file_pattern)
print(files)
for file in files:
    print(file)
    with open(file, "r") as f:
        line = f.readline()
print("----- 끝 -----")

[]
----- 끝 -----

## 2. 파이썬 문자열 다루기

In [131]:
# 양쪽 공백 제거
b1=" 작은 일에 성실한 사람은      큰일에도 성실하고 "
b1.strip()

'작은 일에 성실한 사람은      큰일에도 성실하고'

In [132]:
# 왼쪽 문자, 오른쪽 문자, 양쪽 문자 제거
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
text = text.strip('.')
text

'작은 일에 성실한 사람은, 큰일에도 성실하고'

In [133]:
# ,로 문자열 분리
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
text.strip(".").split(",")

['작은 일에 성실한 사람은', ' 큰일에도 성실하고']

In [134]:
# .으로 문자열 분리
numbers="1. 2. 3. 4. 5. 6"
numbers.split(".")

['1', ' 2', ' 3', ' 4', ' 5', ' 6']

## 3. 판다스로 데이터 가져오기

In [276]:
# 판다스 설치
!pip install pandas

Requirement already satisfied: pandas in C:\Users\user\anaconda3\envs\Pydata26\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\user\anaconda3\envs\Pydata26\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\user\anaconda3\envs\Pydata26\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\user\anaconda3\envs\Pydata26\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\user\anaconda3\envs\Pydata26\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [277]:
# 타이타닉 데이터 가져오기
titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'

In [278]:
# 데이터를 읽으면서 탭을 기준으로 분리하여 데이터 프레임으로 만들기
t_df = pd.read_csv(titanic_data, sep='\t')
t_df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [279]:
# 연습용 sample_data.csv 로딩하기
sample_file = '../data/sample_data.csv'

import pandas as pd
sample_df = pd.read_csv(sample_file)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [280]:
sample_df.to_csv('../data/sample_data_copy.csv', index=False)

In [281]:
df2 = pd.read_csv('../data/sample_data_copy.csv')
df2

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

# 4. 판다스 데이터 처리

### 4-1. 데이터 구조 및 구성 확인

In [282]:
# 앞부분 확인
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [283]:
# 뒷부분 확인
t_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [284]:
# 데이터 개수/형태 확인
t_df.shape

(156, 12)

In [285]:
#데이터의 기본 통계치 보기
t_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [286]:
# 데이터 구성 정보 확인하기
t_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [287]:
# 타이타닉 데이터 구조 및 구성 확인하기
t_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

### 4-2. 컬럼명과 인덱스 정리

In [288]:
# 데이터프레임 복사하기
sample_backup_df = sample_df.copy()
sample_backup_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [289]:
# 열 이름 변경하기 : 모두 소문자로 변경
# new_cols = []
# for col in sample_df.columns:
#    new_cols.append(col.lower())
sample_df.columns = [col.lower() for col in sample_df.columns]
sample_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [290]:
sample_df = sample_df.rename(columns=str.lower)
sample_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [291]:
sample_df = sample_df.rename(columns=str.capitalize)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [292]:
# 컬럼명의 첫글자는 소문자로, 나머지는 대문자로 수정
sample_df.columns = [col[0].lower() + col[1:].upper() for col in sample_df.columns]
sample_df

      nAME   aGE gENDER         cITY
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [293]:
# 컬럼명의 첫글자는 소문자로, 나머지는 대문자로 수정 람다함수로
sample_df = sample_df.rename(columns=lambda x: x[0].lower() + x[1:].upper())
sample_df

      nAME   aGE gENDER         cITY
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [294]:
sample_df = sample_backup_df.copy()
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [295]:
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [296]:
# index 확인
t_df.index

RangeIndex(start=0, stop=156, step=1)

In [297]:
# 행 데이터 삭제하기
drop_index = [2, 4, 152, 154]
t_df = t_df.drop(drop_index, axis=0)
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
149,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [298]:
# index를 0부터 순서대로 assign 되도록 reset하기
t_df = t_df.reset_index(drop=True)
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [299]:
t_df = t_df.rename(columns=str.lower)
t_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [300]:
# 컬럼 PassengeId를 index로 설정하기
t_df = t_df.set_index('passengerid')
t_df

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
passengerid,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...
150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [301]:
# index를 컬럼으로 만들고, index를 RangeIndex로 reset하기
t_df = t_df.reset_index()
t_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

### 4-3. 데이터 정렬

In [302]:
# 'age' 기준으로 정렬
t_df = t_df.sort_values(by='age', ascending=False)
t_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
94,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
114,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
31,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
52,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
92,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
107,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
119,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
124,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
126,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
138,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

In [303]:
# 'age' 기준으로 내림차순으로 정렬
t_df = t_df.sort_values(by='age', ascending=False)
t_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
94,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
114,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
31,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
52,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
92,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
107,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
119,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
124,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
126,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
138,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

In [304]:
# 'age', 'pclass'를 기준으로 정렬
# t_df.sort_values(by=['pclass', 'age'], ascending=False)

# pclass는 오름차순으로 정렬, age는 내림차순으로 정렬
t_df.sort_values(by=['pclass', 'age'], ascending=[True, False])

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
94,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
52,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
9,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
122,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
107,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
119,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
124,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
126,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
138,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

In [305]:
# index를 기준으로 정렬
t_df = t_df.sort_index()
t_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

### 4-4. 데이터 접근/추출
* 범위 지정 : 직접 지정, 인덱서 이용
* 조건 지정

In [306]:
score_dict={'이름': ['정약용', '이순신', '이율곡', '홍길동'],
            '국어' : [70, 100, 90, 85],
            '영어' : [80, 80, 95, 100],
            '수학' : [100, 70, 90, 90]}
score_df = pd.DataFrame(score_dict)
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [307]:
# 행 지정 -> 슬라이싱
score_df[:3]

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   90

In [308]:
# 열 접근
score_df[['이름', '국어']]

    이름   국어
0  정약용   70
1  이순신  100
2  이율곡   90
3  홍길동   85

In [309]:
score_df.이름

0    정약용
1    이순신
2    이율곡
3    홍길동
Name: 이름, dtype: str

In [310]:
# 특정 (행,열)의 데이터 접근
score_df[:2][['이름', '국어']]

    이름   국어
0  정약용   70
1  이순신  100

In [311]:
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [312]:
# 인덱서 이용 : 레이블(이름) 인덱서
# 행 접근
score_df.loc[1]

이름    이순신
국어    100
영어     80
수학     70
Name: 1, dtype: object

In [313]:
# 열 접근
score_df.loc[:, ['이름', '국어']]

    이름   국어
0  정약용   70
1  이순신  100
2  이율곡   90
3  홍길동   85

In [314]:
# (행,열) 접근
score_df.loc[:1, '이름': '수학']

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70

In [315]:
# 인덱서 이용 : 위치(숫자) 인덱서
# 행 접근
score_df.iloc[:1]

    이름  국어  영어   수학
0  정약용  70  80  100

In [316]:
# 열 접근
score_df.iloc[:, 1:3]

    국어   영어
0   70   80
1  100   80
2   90   95
3   85  100

In [317]:
# (행,열) 접근
score_df.iloc[:2, 1:3]

    국어  영어
0   70  80
1  100  80

In [318]:
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [319]:
# 조건 지정 추출 : Boolean Indexing
# 직접 지정 방식으로 행 추출
score_df[score_df.수학 >= 90]

    이름  국어   영어   수학
0  정약용  70   80  100
2  이율곡  90   95   90
3  홍길동  85  100   90

In [320]:
score_df[(score_df.국어 >= 90) & (score_df.수학 >= 90)]

    이름  국어  영어  수학
2  이율곡  90  95  90

In [321]:
score_df[score_df['이름'].isin(['정약용', '이순신'])]

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70

In [322]:
# 인덱서 방식으로 행 추출
score_df.loc[score_df.수학 >= 90]

    이름  국어   영어   수학
0  정약용  70   80  100
2  이율곡  90   95   90
3  홍길동  85  100   90

In [323]:
# (행,열) 데이터 추출
score_df.loc[score_df.수학 >= 90, ['이름', '수학']]

    이름   수학
0  정약용  100
2  이율곡   90
3  홍길동   90

In [324]:
# 열 데이터에 조건 지정
score_df.loc[:, score_df.columns != '영어']

    이름   국어   수학
0  정약용   70  100
1  이순신  100   70
2  이율곡   90   90
3  홍길동   85   90

In [325]:
score_df.loc[:, score_df.dtypes == 'int']

    국어   영어   수학
0   70   80  100
1  100   80   70
2   90   95   90
3   85  100   90

### 171p~181p

In [326]:
# 지정 범위의 행에서 데이터 가져오기
t_df[0:5]
t_df[0:1]
t_df[::3]
t_df[::-1]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [327]:
# 단순 인덱스로 범위 지정해 데이터 가져오기
t_df[:3]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [328]:
# 지정 범위의 열에서 데이터 가져오기
len(t_df.columns)

12

In [329]:
# 첫 번째(0번) 열을 1차원 배열의 Series 객체로 추출
t_df[t_df.columns[0]]

0        1
1        2
2        4
3        6
4        7
      ...
147    150
148    151
149    152
150    154
151    156
Name: passengerid, Length: 152, dtype: int64

In [330]:
# 마지막 열을 1차원 배열의 Series 객체로 추출
t_df[t_df.columns[11]]

0      S
1      C
2      S
3      Q
4      S
      ..
147    S
148    S
149    S
150    S
151    C
Name: embarked, Length: 152, dtype: str

In [331]:
# 열 이름으로 데이터 가져오기
age = t_df['age']
print(type(age))

<class 'pandas.Series'>

In [332]:
# 'age' 열을 1차원 배열인 Series 객체로 추출
t_df['age']
t_df.age

0      22.0
1      38.0
2      35.0
3       NaN
4      54.0
       ...
147    42.0
148    51.0
149    22.0
150    40.5
151    51.0
Name: age, Length: 152, dtype: float64

In [333]:
# 열 이름과 위치를 이용해 데이터 가져오기
print(t_df[t_df.columns[0]][0])
print(t_df['age'][0])
print(t_df[t_df.columns[0]][2])
print(t_df[t_df.columns[-1]][0])
print(t_df[t_df.columns[0]][0])

1
22.0
4
S
1

In [337]:
t_df[t_df.columns[0]][2:6]
t_df[t_df.columns[0]][:-1]
t_df[t_df.columns[0]][::3]
t_df[t_df.columns[0]][-1:]
t_df[t_df.columns[0]][::-1]

151    156
150    154
149    152
148    151
147    150
      ...
4        7
3        6
2        4
1        2
0        1
Name: passengerid, Length: 152, dtype: int64

In [339]:
t_df[['pclass', 'name', 'sex']]
t_df[[t_df.columns[2], t_df.columns[3], t_df.columns[4]]]

     pclass                                               name     sex
0         3                            Braund, Mr. Owen Harris    male
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
3         3                                   Moran, Mr. James    male
4         1                            McCarthy, Mr. Timothy J    male
..      ...                                                ...     ...
147       2                  Byles, Rev. Thomas Roussel Davids    male
148       2                         Bateman, Rev. Robert James    male
149       1                  Pears, Mrs. Thomas (Edith Wearne)  female
150       3                    van Billiard, Mr. Austin Blyler    male
151       1                        Williams, Mr. Charles Duane    male

[152 rows x 3 columns]

In [340]:
t_df[[t_df.columns[2], t_df.columns[3], t_df.columns[4]]][2:15:3]

    pclass                                          name     sex
2        1  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
5        3                Palsson, Master. Gosta Leonard    male
8        3               Sandstrom, Miss. Marguerite Rut  female
11       3                   Andersson, Mr. Anders Johan    male
14       3                          Rice, Master. Eugene    male

In [341]:
print(t_df[t_df.columns[0]][0])
print(t_df[t_df.columns[0]][2])
# print(t_df[t_df.columns[0]][-1]) -> 실행 시 오류 발생
type(t_df[t_df.columns[0]][0])

1
4

numpy.int64

In [342]:
# 인덱스 이름을 기준으로 데이터 가져오기: loc 속성
t_df.loc[0]

passengerid                          1
survived                             0
pclass                               3
name           Braund, Mr. Owen Harris
sex                               male
age                               22.0
sibsp                                1
parch                                0
ticket                       A/5 21171
fare                              7.25
cabin                              NaN
embarked                             S
Name: 0, dtype: object

In [343]:
t_df.loc[0:5]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [344]:
t_df.loc[0:10:2]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
6,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
8,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
10,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S

In [345]:
t_df.loc[:, 'age']

0      22.0
1      38.0
2      35.0
3       NaN
4      54.0
       ...
147    42.0
148    51.0
149    22.0
150    40.5
151    51.0
Name: age, Length: 152, dtype: float64

In [346]:
t_df.loc[:, ['age', 'sex']]

      age     sex
0    22.0    male
1    38.0  female
2    35.0  female
3     NaN    male
4    54.0    male
..    ...     ...
147  42.0    male
148  51.0    male
149  22.0  female
150  40.5    male
151  51.0    male

[152 rows x 2 columns]

In [347]:
t_df.loc[3:7, ['age', 'sex']]

    age     sex
3   NaN    male
4  54.0    male
5   2.0    male
6  27.0  female
7  14.0  female

In [348]:
t_df.loc[2:5, 'survived' : 'age']

,survived,pclass,name,sex,age
2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
3,0,3,"Moran, Mr. James",male,NaN
4,0,1,"McCarthy, Mr. Timothy J",male,54.0
5,0,3,"Palsson, Master. Gosta Leonard",male,2.0

In [349]:
# 인덱스 순서를 기준으로 데이터 가져오기 : iloc 속성
t_df.iloc[0]

passengerid                          1
survived                             0
pclass                               3
name           Braund, Mr. Owen Harris
sex                               male
age                               22.0
sibsp                                1
parch                                0
ticket                       A/5 21171
fare                              7.25
cabin                              NaN
embarked                             S
Name: 0, dtype: object

In [350]:
t_df.iloc[0:5]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [351]:
t_df.iloc[0:10:3]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [352]:
t_df.iloc[:, [0, 2]]

     passengerid  pclass
0              1       3
1              2       1
2              4       1
3              6       3
4              7       1
..           ...     ...
147          150       2
148          151       2
149          152       1
150          154       3
151          156       1

[152 rows x 2 columns]

In [353]:
t_df.iloc[1:5, [0,2]]

   passengerid  pclass
1            2       1
2            4       1
3            6       3
4            7       1

In [355]:
t_df.iloc[1:5, 1:4]

   survived  pclass                                               name
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
3         0       3                                   Moran, Mr. James
4         0       1                            McCarthy, Mr. Timothy J

## 4-5. 그룹별로 요약하여 데이터 확인
* value_counts()
* groupby()
* pivot_table()

In [334]:
sample_file = 'data/sales_sample.csv'

In [335]:
# 샘플 파일 로딩

In [336]:
# 지역별 판매 기록의 개수

In [ ]:
# 상품별 판매 기록의 개수와 비율

In [ ]:
# 지역과 상품의 조합별 판매 기록 개수

In [ ]:
# 지역별 총매출

In [ ]:
# 상품별 평균 매출

In [ ]:
# 지역별 판매수량의 합계와 매출의 합계

In [ ]:
# 지역과 상품별 평균 매출

In [ ]:
# 지역별·상품별 총매출을 구하고 행과 열의 합계 표시